UPDATE GEO_AREA
SET POPULATION = 9500000
WHERE AREA_ID = 11;

UPDATE MANDATE
SET MANDATE_TYPE = 'EXCLUSIVE'
WHERE MANDATE_ID = 401;

UPDATE MANDATE
SET END_DATE = '2027-01-10'
WHERE MANDATE_ID = 401;

SELECT * FROM AGENT;

SELECT * FROM AGENCY;

SELECT * FROM GEO_AREA;

UPDATE AGENT
SET PHONE_NUMBER = '9998887776'
WHERE AGENT_TAX_ID = 201;

UPDATE GEO_AREA
SET POPULATION = 20000000
WHERE AREA_ID = 11;

UPDATE MANDATE
SET MANDATE_TYPE = 'Rent'
WHERE MANDATE_ID = 401;

UPDATE MANDATE
SET END_DATE = '2025-12-31'
WHERE MANDATE_ID = 401;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM MANDATE
WHERE END_DATE < CURDATE();

SET SQL_SAFE_UPDATES = 1;

SELECT * FROM MANDATE
WHERE END_DATE < CURDATE();

SELECT * FROM AGENT;

SELECT AGENCY_ID, ADDRESS, AGENCY_TYPE
FROM AGENCY;

SELECT * FROM GEO_AREA;

SELECT COUNT(*) AS TOTAL_AGENTS
FROM AGENT;

SELECT COUNT(*) AS TOTAL_AGENCIES
FROM AGENCY;

SELECT COUNT(*) AS TOTAL_MANDATES
FROM MANDATE;

SELECT
    AGENT_TAX_ID,
    COUNT(MANDATE_ID) AS TOTAL_MANDATES_HANDLED
FROM MANDATE
GROUP BY AGENT_TAX_ID;

SELECT
    AGENCY_ID,
    COUNT(MANDATE_ID) AS TOTAL_MANDATES_ISSUED
FROM MANDATE
GROUP BY AGENCY_ID;

SELECT
    AVG(DATEDIFF(END_DATE, START_DATE)) AS AVG_DURATION_DAYS
FROM MANDATE;
