CREATE DATABASE REALSTATE_AGENT;
USE REALSTATE_AGENT;

CREATE TABLE AGENT(
AGENT_TAX_ID INT PRIMARY KEY,
AGENT_NAME VARCHAR(20),
PHONE_NUMBER VARCHAR(20),
EMAIL VARCHAR(30)
);

CREATE TABLE GEO_AREA (
AREA_ID INT PRIMARY KEY,
MAIN_CITY VARCHAR(20),
POPULATION INT,
AREA_SQ_KM VARCHAR(20)
);

CREATE TABLE AGENCY(
AGENCY_ID INT PRIMARY KEY,
ADDRESS TEXT,
AGENCY_TYPE VARCHAR(20)
);

CREATE TABLE INDPENDENT_AGNECY(
AGENCY_ID INT,
OWNER_TAX_ID INT,
FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY(AGENCY_ID)
);

CREATE TABLE FRANCHISE_AGENCY(
AGENCY_ID INT,
FRANCHISE_NAME VARCHAR(20),
FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY(AGENCY_ID)
);

CREATE TABLE MANDATE(
MANDATE_ID INT PRIMARY KEY,
AGENT_TAX_ID INT,
AGENCY_ID INT,
START_DATE DATE,
END_DATE DATE,
MANDATE_TYPE VARCHAR(20),
FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY(AGENCY_ID),
FOREIGN KEY (AGENT_TAX_ID) REFERENCES AGENT(AGENT_TAX_ID),
CONSTRAINT CHK_DATA_RANGE CHECK (END_DATE>START_DATE)
);
